# Symlink
#   ln -s ~/.config/zsh/zshrc ~/.zshrc

source ~/.config/zsh/proxy.zsh
source ~/.config/zsh/homebrew.zsh
source ~/.config/zsh/env.zsh

source ~/.config/zsh/zimfw.zsh
source ~/.config/zsh/zle-vi-cursor.zsh 

source ~/.config/zsh/duration-info.zsh
source ~/.config/zsh/fzf.zsh
source ~/.config/zsh/fzf-tab.zsh
source ~/.config/zsh/lazygit.zsh
source ~/.config/zsh/zsh-easymotion/zsh-easymotion.zsh

source ~/.config/zsh/iterm2.zsh

source ~/.config/zsh/bindkey.zsh #< key bindings are reset here
source ~/.config/zsh/alias.zsh

# Add the 'function' subdirectory to Zsh's function search path (fpath).
fpath+=(~/.config/zsh/function)
# Autoload all executable files in the function/ directory as Zsh functions.
# (.:t) means: only regular files (.), and take basename (:t) for autoload name.
autoload -U ~/.config/zsh/function/*(.:t)
